//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: ProtoSource/merged.proto
namespace User
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InitPlayer")]
  public partial class InitPlayer : global::ProtoBuf.IExtensible
  {
    public InitPlayer() {}
    
    private bool _IsNewPlayer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"IsNewPlayer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsNewPlayer
    {
      get { return _IsNewPlayer; }
      set { _IsNewPlayer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}